
spring:
    jpa:
        open-in-view: true
        show-sql: true
        hibernate:
            ddl-auto: create-drop

    output:
        ansi:
            enabled: always
    h2:
        console:
            enabled: true

    datasource:
        driver-class-name: org.h2.Driver
        url: jdbc:h2:mem:health
        username: sa
        password:



