# profile name = dev, prod
spring:
  profiles:
    group:
      "test": "test, datasource"
      "local": "local, datasource, oauth"
      "dev": "dev, datasource, oauth"
      "prod": "dev, datasource, oauth"
    active: dev
