spring:
  config:
    activate:
      on-profile: "local"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:h2:~/Healther
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.health.healther.config.UpperCaseNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
