spring:
  config:
    activate:
      on-profile: "dev"

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: com.health.healther.config.UpperCaseNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
